Introducing support for telemetry-collectors-enabled flag
opensearch-project/performance-analyzer-commons pull request #74
Opened 2024-05-31 05:51 UTC by atharvasharma61

**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
Issue details to be added

**Describe the solution you are proposing**
Introducing support to read telemetry-collectors-enabled flag value from performance-analyzer.properties

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-05 12:08 UTC, Gaganjuneja requested changes

2024-06-05 12:08 UTC, Gaganjuneja commented on src/main/java/org/opensearch/performanceanalyzer/commons/collectors/TelemetryCollector.java
> +public interface TelemetryCollector {}
java doc please.

2024-06-05 12:08 UTC, Gaganjuneja commented on src/main/java/org/opensearch/performanceanalyzer/commons/collectors/ScheduledMetricCollectorsExecutor.java
> +                    || (collectorsSetting == Util.CollectorMode.OTEL.getValue());
Can we please keep the names in sync like here OTEL should be replaced with telemetry or RTF.

2024-06-05 12:08 UTC, Gaganjuneja commented on src/main/java/org/opensearch/performanceanalyzer/commons/util/Util.java
> +    public enum CollectorMode {
java doc please.

2024-06-05 13:10 UTC, Gaganjuneja submitted a review, later dismissed

2024-06-06 06:11 UTC, nishchay21 commented on src/main/java/org/opensearch/performanceanalyzer/commons/collectors/ScheduledMetricCollectorsExecutor.java
>  public class ScheduledMetricCollectorsExecutor extends Thread {
lets add documentation on classes where missing during PR

2024-06-08 11:13 UTC, nishchay21 approved these changes

2024-06-10 16:10 UTC, Gaganjuneja approved these changes

2024-06-10 16:11 UTC, merged